version: "3"

services:
  app:
    image: kopiro/netbsc
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./app:/app
    env_file:
      - .env
