version: '3'

services:
  app:
    image: registry.kopiro.it/netbsc
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./app:/app
    env_file:
      - .env